---
- hosts: webservers
  become: yes
  vars_files:
    - group_vars/all.yml
    - group_vars/webservers/vault.yml

  tasks:
    - name: Install PostgreSQL client and dependencies
      apt:
        name:
          - postgresql-client
          - python3-psycopg2
        state: present
        update_cache: yes

    - name: Create PostgreSQL SSL directory
      file:
        path: /root/.postgresql
        state: directory
        mode: 0700

    - name: Install Yandex Cloud root certificate
      template:
        src: templates/postgresql/root.crt.j2
        dest: /root/.postgresql/root.crt
        mode: 0600

    - name: Verify database connection
      postgresql_query:
        login_host: "{{ db_hosts[0] }}"
        login_port: "{{ db_port }}"
        login_user: "{{ db_user }}"
        login_password: "{{ vault_db_password }}"
        ssl_mode: verify-full
        ca_cert: /root/.postgresql/root.crt
        query: "SELECT version();"
      register: db_check
      changed_when: false

    - name: Create Redmine environment file
      template:
        src: templates/redmine.env.j2
        dest: /opt/redmine/redmine.env
        mode: 0600
      vars:
        db_connection_string: |
          host={{ db_hosts|join(',') }} 
          port={{ db_port }}
          sslmode=verify-full
          dbname={{ db_name }}
          user={{ db_user }}
          password={{ vault_db_password }}
          target_session_attrs=read-write

    - name: Deploy Redmine container
      docker_container:
        name: redmine
        image: redmine:latest
        state: started
        restart_policy: unless-stopped
        env_file: /opt/redmine/redmine.env
        volumes:
          - /opt/redmine/files:/usr/src/redmine/files
          - /root/.postgresql:/usr/src/redmine/.postgresql:ro