---
collections:
  - name: community.postgresql
    version: 3.0.0
  
  - name: community.docker
    version: 3.0.2
  
  - name: datadog.datadog
    version: 4.12.0  # Попробуем более новую версию

roles:
  - name: geerlingguy.docker
    version: 6.0.1