---
collections:
  - name: community.postgresql
    version: 2.0.1
  
  - name: geerlingguy.pip
    version: 0.1.0
  
  - name: datadog.datadog
    version: 4.10.0

roles:
  - name: geerlingguy.docker
    version: 6.0.1