---
collections:
  - name: community.postgresql
    version: 3.0.0  # Используем последнюю стабильную версию
  
  - name: community.docker
    version: 3.0.2
  
  - name: datadog.datadog
    version: 4.10.0

roles:
  - name: geerlingguy.docker
    version: 6.0.1